tasks:
  - name: terraform
    before: |
      cd $PROJECT_ROOT
      source ./bin/tf_alias
      ./bin/terraform-install
      ./bin/generate_tf_credentials
      cd /workspace/terraform-beginner-bootcamp-2023 ; cp terraform.tfvars.example terraform.tfvars
      source ./bin/build_provider
  - name: sinatra
    before: | 
      cd $PROJECT_ROOT
      cd terratowns_mock_server
      bundle install
      bundle exec ruby server.rb 
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd $PROJECT_ROOT
      ./bin/aws-install
      cd $THEIA_WORKSPACE_ROOT
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
    - mcright.auto-save
    - yzhang.markdown-all-in-one
    - mhutchie.git-graph
    - phil294.git-log--graph
    - golang.go
